# GitHub Actions workflow to build, test and publish Python packages to PyPI everytime a new release is created.

name: Publish release

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # We use Python 3.10 here because it's the minimum Python version supported by this library.
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install --upgrade pip build

      - name: Build package
        run: python -m build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist_packages
          path: dist/

  test:
    # This job tests the built package by installing it via pip and running unit tests (without tox).
    name: Test package
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set timezone to Europe/Berlin
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Berlin"

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist_packages
          path: dist/

      - name: Install test dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Install built package
        run: pip install dist/parkapi_sources-*.whl

      - name: Run unit tests
        run: python -m pytest

  publish:
    name: Publish package
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist_packages
          path: dist/

      - name: Upload package to GitHub release assets
        uses: AButler/upload-release-assets@v3.0
        with:
          files: dist/*
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.9.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
