name: lint

on:
  pull_request:
    branches:
      - '*'
  # make workflow "callable" by others
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup Python v3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: pip install
      run: pip install -r requirements.txt -r requirements-dev.txt

    - name: lint using ruff
      # We could also use the official GitHub Actions integration.
      # https://beta.ruff.rs/docs/usage/#github-action
      # uses: chartboost/ruff-action@v1
      run: ruff check --output-format github ./src ./tests

    - name: format check using ruff
      # We could also use the official GitHub Actions integration.
      # https://beta.ruff.rs/docs/usage/#github-action
      # uses: chartboost/ruff-action@v1
      run: |
        ruff format --check ./src ./tests

  test:
    runs-on: ubuntu-latest

    steps:

    - name: set timezone
      uses: szenius/set-timezone@v2.0
      with:
        timezoneLinux: "Europe/Berlin"

    - name: checkout
      uses: actions/checkout@v4

    - name: setup Python v3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: pip install
      run: pip install -r requirements.txt -r requirements-dev.txt

    - name: run pytest
      run: python -m pytest tests
